workflows:
  flutter-ios-simulator:
    name: Flutter iOS Simulator
    environment:
      flutter: 3.27.3
      xcode: 16.2
    scripts:
      - name: Run Flutter pub get

        script: flutter pub get

      - name: Build unsigned .app for simulator

        script: flutter build ios --simulator --build-name=1.0.0 --build-number=2

    artifacts:

      - build/ios/iphonesimulator/Runner.app
