name: iOS Flutter CI

on:
  push:
    branches:
      - '**'

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 120

    env:
      APP_ID: 6677026826
      FLUTTER_CHANNEL: stable

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup flutter stable
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.10.6  # Fixed known arm64 compatible version

    - name: Update Flutter to latest stable (workaround for arm64)
      run: |
        cd $FLUTTER_ROOT
        git fetch --tags
        git checkout $(curl -s https://storage.googleapis.com/flutter_infra_release/releases/releases_${FLUTTER_CHANNEL}.json | jq -r '.current_release.version')
        flutter --version

    - name: Flutter pub get
      run: flutter pub get

    - name: Activate FlutterFire CLI and Melos
      run: |
        dart pub global activate flutterfire_cli || echo "FlutterFire CLI activation failed, continuing..."
        dart pub global activate melos || echo "Melos activation failed, continuing..."
        melos bootstrap || echo "Melos bootstrap failed, continuing..."

    - name: Machine Specs
      run: |
        sysctl -n machdep.cpu.brand_string
        sysctl -n hw.physicalcpu
        sysctl -n hw.logicalcpu
        sysctl -n hw.memsize

    - name: Install CocoaPods
      run: |
        cd ios
        pod install --repo-update

    - name: Run flutter analyze
      run: flutter analyze

    - name: Run flutter tests
      run: flutter test
      continue-on-error: true

    - name: Get latest app store build number and build ipa
      run: |
        BUILD_NUMBER=$(($(bash <(curl -s https://raw.githubusercontent.com/codemagic-ci-cd/codemagic-cli/main/scripts/app-store-connect/get-latest-build-number.sh) $APP_ID) + 1))
        flutter build ipa --release \
          --build-name=1.0.$BUILD_NUMBER \
          --build-number=$BUILD_NUMBER \
          --export-options-plist=ios/export_options.plist
