name: iOS Workflow

on:
  push:
    branches:
      - '**'

jobs:
  build-ios:
    name: Build and Test iOS
    runs-on: macos-latest
    timeout-minutes: 120

    env:
      FLUTTER_VERSION: stable
      APP_ID: 6677026826

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    # Simulate the Melos & bootstrap script (FlutterFire & Melos might require setup)
    - name: Setup Flutter environment and dependencies
      run: |
        echo "FLUTTER_ROOT is set to: $FLUTTER_ROOT"
        echo "Running flutter pub get"
        flutter pub get

        dart pub global activate flutterfire_cli || echo "FlutterFire CLI activation failed, continuing..."
        dart pub global activate melos || echo "Melos activation failed, continuing..."
        melos bootstrap || echo "Melos bootstrap failed, continuing..."

    - name: Machine Specs
      run: |
        system_profiler SPHardwareDataType

    - name: Install CocoaPods dependencies
      run: pod install --repo-update
      working-directory: ios

    - name: Run flutter analyze
      run: flutter analyze

    - name: Run flutter tests
      run: flutter test
      continue-on-error: true

    - name: Increment build number and build IPA
      run: |
        BUILD_NUMBER=$(bash <(curl -s https://raw.githubusercontent.com/codemagic-ci-cd/codemagic-cli/main/scripts/app-store-connect/get-latest-build-number.sh) $APP_ID)
        BUILD_NUMBER=$((BUILD_NUMBER + 1))
        echo "Building IPA with build number: $BUILD_NUMBER"
        flutter build ipa --release \
          --build-name=1.0.$BUILD_NUMBER \
          --build-number=$BUILD_NUMBER \
          --export-options-plist=ios/export_options.plist
