name: iOS Flutter Unsigned Build

on:
  push:
    branches: ['**']

jobs:
  build-ios-unsigned:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter test
        run: flutter test

      - name: Build unsigned ipa
        run: flutter build ipa --no-codesign --release
