name: iOS Unsigned Flutter Build

on:
  push:
    branches:
      - '**'

jobs:
  build-ios-unsigned:
    runs-on: macos-latest
    timeout-minutes: 90

    env:
      APP_ID: 6677026826

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Activate FlutterFire CLI and Melos
        run: |
          dart pub global activate flutterfire_cli || echo "FlutterFire CLI activation failed, continuing..."
          dart pub global activate melos || echo "Melos activation failed, continuing..."
          melos bootstrap || echo "Melos bootstrap failed, continuing..."

      - name: Get Flutter packages
        run: flutter pub get

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter unit tests
        run: flutter test
        continue-on-error: true

      - name: Build unsigned IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-unsigned-ipa
          path: build/ios/ipa/*.ipa
